name: libraries

on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.13"
      - name: Install Poetry
        uses: snok/install-poetry@main
      - name: Install dependencies
        run: poetry install
      - run: poetry run pytest
        working-directory: test