name: libraries

on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install Poetry
        uses: snok/install-poetry@main
      - name: Install dependencies
        run: poetry install --all-extras
      - run: poetry run pytest
        working-directory: test