# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: libraries

on:
  push:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: "3.13"
    - name: Install Poetry
      uses: snok/install-poetry@main
    - name: Install dependencies
      run: poetry install
    - run: pipx install pytest
    - name: Test with pytest
      run: pytest
      working-directory: test
