on:
  push:

jobs:
  win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - run: ./poetry/admin.ps1 Install-Poetry
      - uses: astral-sh/setup-uv@main
        with:
          version: 'latest'
      - run: uv sync --extra poetry
      - run: uv run python tests/poetry/test_.py
        
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: ./poetry/admin.sh install
      - uses: astral-sh/setup-uv@main
        with:
          version: 'latest'
      - run: uv sync --extra poetry
      - run: uv run python tests/poetry/test_.py
  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
      - uses: astral-sh/setup-uv@main
        with:
          version: 'latest'
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: uv sync --extra poetry
      - run: uv run python tests/poetry/test_.py