on:
  workflow_dispatch:

name: publish
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: snok/install-poetry@main
      - run: poetry build
      - run: poetry config http-basic.pypi __token__ ${{secrets.PYPI_TOKEN}}
      - run: poetry publish --skip-existing
  poetry-util:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/poetry-buildpack@main
        with:
          working-directory: .
      - run: poetry run build-poetry
        shell: bash
      - run: .\tests\poetry\test.ps1
      - uses: softprops/action-gh-release@master
        with:
          name: poetry-util
          files: dist/poetry.exe
          tag_name: poetry-util