on:
  workflow_dispatch:
  push:
name: publish
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: astral-sh/setup-uv@main
        with:
          version: 'latest'
      - run: uv build
      - run: uv publish --token ${{secrets.PYPI_TOKEN}}
  poetry-util:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/uv-buildpack@main
        with:
          working-directory: .
      - run: uv run build-poetry
        shell: bash
      - run: .\tests\poetry\test.ps1
      - uses: softprops/action-gh-release@master
        with:
          files: dist/poetry-util.exe
          tag_name: poetry-util